[features]
seeds = false

[programs.devnet]
hello_clockwork = "6xSDvHor2VRp6dvpwsmzVhxQdMqk3mdYbqBJuncbLMme"

[programs.localnet]
hello_clockwork = "6xSDvHor2VRp6dvpwsmzVhxQdMqk3mdYbqBJuncbLMme"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
